### ISSUE TITLE
Initialization of super class fails

### ISSUE THREAD

**Issue by mali-git** [SmartDataAnalytics/POEM#1]
It should be a simple error, but I don't see it.

https://github.com/SmartDataAnalytics/POEM/blob/26306431f63d0784de56e88ebc483399f3fac0fc/src/poem/instance_creation_factories/triples_numeric_literals_factory.py#L17

I also tried: 
`super().__init__(config)`

**Comment by cthoyt** [comment]
Correct solution is `super().__init__(self, config)`
